%% ========================================================
%  FIGURE 5: Impairment of the CSF outflow pathways (A2) together with the two
%  combined-pathology scenarios (A3): 16 scenarios in total.
%  Vertical two-panel layout:
%    (a) heatmap of five variables, % change vs baseline
%    (b) stacked bar of the three efflux pathway shares
%
%  The 14 A2 scenarios form a complete 2^3 factorial design: each of the three
%  absorption pathways (O = olfactory lymphatic / R_CP, V = arachnoid
%  granulation / R_AG, S = spinal lymphatic / R_SPI) is raised by alpha = 2.5
%  or 5, singly, in pairs and all together.  Rows of (a) and bars of (b) share
%  the same order single -> dual -> triple so the two panels can be read
%  vertically against each other.
%
%  The last two columns belong to group A3 and are set apart by a heavier rule:
%  H+C = H_C (chronic grade-2 hypertension on the severe triple impairment) and
%  HA+C = HA_C (the acute counterpart: same arterial pressure and same triple
%  impairment, with PVI and the vascular/BBB state at baseline).
%
%  Style follows MATLAB_script/DrawResult0520/ResultDraw.m: same diverging
%  colormap endpoints as the Fig7 heatmap, same path colours as the pie/stack
%  panels, same 1.5x font scale as Fig3/Fig4.
%
%  Data: SimulinkModel/Results/collate_all.csv (scenario means, regenerated by
%        Batch/collate_all.m).
%  Output: PDF only into <root>/新插图/, plus a copy of this script.
%
%  Usage: matlab -batch "draw_fig_comm_hydro"
% ========================================================
function draw_fig_comm_hydro(csvFile, outPdf)
here = fileparts(mfilename('fullpath'));
root = fileparts(fileparts(here));
addpath(here);

if nargin < 1 || isempty(csvFile)
    csvFile = fullfile(root,'SimulinkModel','Results','collate_all.csv');
end
if nargin < 2 || isempty(outPdf)
    outPdf = fullfile(root,'新插图','Fig5_CommHydro.pdf');
end
if ~exist(fileparts(outPdf),'dir'), mkdir(fileparts(outPdf)); end

%% ── 场景定义（2^3 因子设计，单路 -> 双路 -> 三路 -> A3 组合）──────
CODES  = {'C_O2.5','C_O5','C_V2.5','C_V5','C_S2.5','C_S5', ...
          'C_OV2.5','C_OV5','C_OS2.5','C_OS5','C_VS2.5','C_VS5', ...
          'C_OVS2.5','C_OVS5','H_C','HA_C'};
GRPEND = [6 12 14 16];                    % 分组分界（用于分隔线与标签）
GRPLAB = {'single pathway','two pathways','three pathways','A3 combined'};
BASE   = 'B';
SHORT  = cellfun(@(s) regexprep(s,'^C_',''), CODES, 'UniformOutput', false);  % 显示时省掉 C_ 前缀
SHORT{end-1} = 'H+C';                     % A3：慢性 G2 高血压 + 三通路重度受损
SHORT{end}   = 'HA+C';                    % A3：急性 G2 高血压 + 同一三通路重度受损
NCOMB  = numel(CODES);                    % 末列列号
LW_SEP = 1.6;  LW_SEP_LAST = 2.6;         % A3 组前的分隔线加粗，表示不属于因子设计
LEG_UP = 0.3;                             % (b) 图例相对 'north' 再上移的字符高度数

% 热图行：两个流入量、两个流出量、一个压力（V_VEN 已移出：A2 与 A3 都不含弹性改变，
% 该行全为 0，无对照价值）
QCOLS  = {'Q_GS','Q_BBB','Q_PAS','Q_SPI','P_ECS'};
SHCOLS = {'pct_Q_OLS','pct_Q_SSS','pct_Q_SLS'};

FONT_SCALE = 1.5;
fs_tick = 12; fs_title = 9*FONT_SCALE; fs_cell = 9.5; fs_ax = 15;
fs_xtick = 11;   % 横轴 15 个代号（最长 OVS2.5），字号须能互不重叠——见文末间距自检

fprintf('=== draw_fig_comm_hydro ===\n  数据: %s\n  输出: %s\n', csvFile, outPdf);

%% ── 读表 ──────────────────────────────────────────────
T = readtable(csvFile, 'VariableNamingRule','preserve');
if ~ismember('code', T.Properties.VariableNames)
    error('draw_fig_comm_hydro:badCsv','%s 缺 code 列', csvFile);
end
codesAll = string(T.code);
iB = find(codesAll == BASE, 1);
if isempty(iB), error('draw_fig_comm_hydro:noBase','表里找不到基线行 %s', BASE); end
iS = zeros(1,numel(CODES));
for k = 1:numel(CODES)
    i = find(codesAll == string(CODES{k}), 1);
    if isempty(i), error('draw_fig_comm_hydro:noRow','表里缺少场景 %s', CODES{k}); end
    iS(k) = i;
end
fprintf('  基线行 %s，共 %d 个场景（C 组 14 + 组合 1）全部找到\n', BASE, numel(iS));

getq = @(col, idx) local_col(T, col, idx);
M = zeros(numel(CODES), numel(QCOLS));      % % change vs baseline
for c = 1:numel(QCOLS)
    vb = getq(QCOLS{c}, iB);
    vs = getq(QCOLS{c}, iS);
    M(:,c) = 100*(vs/vb - 1);
end

SH = zeros(numel(CODES), 3);                % 三通路占比 (%)
for c = 1:3
    SH(:,c) = getq(SHCOLS{c}, iS);
end
shSum = sum(SH,2);
if any(abs(shSum-100) > 0.5)
    warning('占比之和偏离 100%%：最大偏差 %.2f', max(abs(shSum-100)));
end
shBase = [getq('pct_Q_OLS', iB), getq('pct_Q_SSS', iB), getq('pct_Q_SLS', iB)];
fprintf('  基线占比 O/V/S = %.2f / %.2f / %.2f\n', shBase);
fprintf('  热图 %% 变化范围: %.1f .. %.1f\n', min(M(:)), max(M(:)));

%% ── 配色 ──────────────────────────────────────────────
C.white = [1 1 1];
C.path.lymph  = hsv2rgb([0.33, 0.4, 0.75]);
C.path.ag     = hsv2rgb([0.58, 0.4, 0.75]);
C.path.spinal = hsv2rgb([0.78, 0.4, 0.75]);
C.path.bbbStack = [0.62 0.62 0.62];   % BBB 倒流层（灰），与 0520 代码一致
C.bar.edge = [0.35 0.35 0.35];  C.bar.edgeWidth = 0.6;
HM.negEnd = [0.35 0.55 0.72];   % 与 DrawResult0520 的 Fig7 热图一致
HM.posEnd = [0.75 0.28 0.24];
HM.textWhiteIf = 55;            % |值| 超过此值时单元格文字转白
HM.clim = 100;                  % 对称色标 ±100%，超出者饱和显示（数值仍然标出）

cmap = local_diverging(512, HM.negEnd, C.white, HM.posEnd);

%% ── 图形：上下两栏 ────────────────────────────────────
set(groot,'DefaultAxesFontName','Arial'); set(groot,'DefaultTextFontName','Arial');
fig = figure('Name','Fig5_CommHydro','NumberTitle','off', ...
    'Units','centimeters','Position',[3 2 26 20], ...
    'Color',C.white,'PaperPositionMode','auto');
set(fig,'DefaultAxesFontSize',fs_tick,'DefaultTextFontSize',fs_tick);
tl = tiledlayout(fig, 2, 1, 'TileSpacing','compact','Padding','compact');

%% ── (a) 热图（横轴 = 场景，纵轴 = 参数）───────────────
ax = nexttile(tl);
imagesc(ax, 1:numel(CODES), 1:numel(QCOLS), M.');   % M 为 场景×参数，转置成 参数×场景
set(ax, 'YDir','reverse');
colormap(ax, cmap);  clim(ax, [-HM.clim HM.clim]);
% 纵轴 = 量符号（tex 下标）；横轴 = 实验代号（tex 下下划线要转义）
% 显示名与论文/图3统一：CSV 列名仍是 Q_GS / Q_ECS，图上显示 Q_{GS} / Q_{ECS}
QLAB = {'Q_{GS}','Q_{BBB}','Q_{PAS}','Q_{SPI}','P_{ECS}'};   % 顺序必须与 QCOLS 一一对应
if numel(QLAB) ~= numel(QCOLS)
    error('draw_fig_comm_hydro:labMismatch','QLAB 与 QCOLS 数量不一致');
end
ylab = QLAB;
xlab = strrep(SHORT, '_', '\_');
set(ax, 'XTick',1:numel(CODES), 'XTickLabel',xlab, 'XTickLabelRotation',0, ...
        'YTick',1:numel(QCOLS), 'YTickLabel',ylab, ...
        'TickLabelInterpreter','tex', 'FontSize',fs_tick, ...
        'XGrid','off','YGrid','off', ...          % 网格改由下面的边界线绘制
        'Box','on','LineWidth',0.8);
ax.XAxis.FontSize = fs_xtick;      % 15 个代号横排，横轴字号略降（间距自检见文末）
xlim(ax, [0.5 numel(CODES)+0.5]);  ylim(ax, [0.5 numel(QCOLS)+0.5]);
% 单元格边界：imagesc 的刻度在格子中心，所以要显式画在 0.5 半整数处
for xv = 1.5:numel(CODES)-0.5
    xline(ax, xv, '-', 'Color',[0.80 0.80 0.80], 'LineWidth',0.5, 'HandleVisibility','off');
end
for yv = 1.5:numel(QCOLS)-0.5
    yline(ax, yv, '-', 'Color',[0.80 0.80 0.80], 'LineWidth',0.5, 'HandleVisibility','off');
end
% 单元格数值
for r = 1:numel(QCOLS)
    for c = 1:numel(CODES)
        v = M(c,r);
        if isnan(v), continue; end
        if abs(v) < 0.5, txt = '0'; else, txt = sprintf('%.0f', v); end   % 避免出现 "-0"
        if abs(v) > HM.textWhiteIf, tc = C.white; else, tc = [0.12 0.12 0.12]; end
        text(ax, c, r, txt, 'HorizontalAlignment','center', ...
            'VerticalAlignment','middle','FontSize',fs_cell,'Color',tc, ...
            'FontWeight','bold','Clipping','on');
    end
end
% 分组分隔线：单路(1-6) / 双路(7-12) / 三路(13-14) / 组合(15，加粗)
for g = 1:numel(GRPEND)-1
    if g == numel(GRPEND)-1, lw = LW_SEP_LAST; else, lw = LW_SEP; end
    xline(ax, GRPEND(g)+0.5, '-', 'Color',[0.1 0.1 0.1], 'LineWidth',lw, ...
          'HandleVisibility','off');
end
cb = colorbar(ax);                   % 只属于 (a) 这一行
cb.Label.String = '% change vs baseline';
cb.FontSize = fs_tick;                % 先设刻度字号（会按倍率重算标签字号）
cb.Label.FontSize = fs_ax;             % 再显式设标签字号=轴标签(15)
title(ax, '(a)  Variable Changes Across Outflow Impairment and Combined Pathology', ...
      'FontWeight','bold','FontSize',fs_title);
ax_a = ax;

%% ── (b) 出口流量堆叠柱（绝对流量 + Q_BBB 倒流时的灰色补偿层）──
ax = nexttile(tl);  hold(ax,'on');
FCOLS = {'Q_OLS','Q_SSS','Q_SLS'};
FL = zeros(numel(CODES),3);
for c = 1:3, FL(:,c) = getq(FCOLS{c}, iS); end
qBBB    = getq('Q_BBB', iS);
bbbOut  = max(0, -qBBB);          % Q_BBB < 0 表示流体由 ECS 经 BBB 回流入血 = 新增出口
ST      = [FL, bbbOut];
layerLabels = {'Q_{OLS}','Q_{SSS}','Q_{SLS}'};
layerColors = [C.path.lymph; C.path.ag; C.path.spinal];
hasBBB = any(bbbOut > 1e-9);
if hasBBB
    layerLabels{end+1} = 'Q_{BBB} (reversed)';
    layerColors = [layerColors; C.path.bbbStack];      % 灰色，与 0520 代码一致
end
bh = bar(ax, 1:numel(CODES), ST, 'stacked', 'EdgeColor',C.bar.edge, ...
         'LineWidth',C.bar.edgeWidth, 'BarWidth',0.72);
for li = 1:numel(bh), bh(li).FaceColor = layerColors(li,:); end
totOut = sum(ST,2)';
% 基线累计参考线（0.156 / 0.260 mL/min，即基线的 46% 与 78% 分位）
cumBase = cumsum([getq('Q_OLS',iB), getq('Q_SSS',iB)]);   % 基线累计：前两条通路
hBaseTxt = gobjects(1,numel(cumBase));
for k = 1:numel(cumBase)
    yline(ax, cumBase(k), '--', 'Color',[0.25 0.25 0.25], 'LineWidth',1.1, ...
          'HandleVisibility','off');
    hBaseTxt(k) = text(ax, NCOMB+0.55, cumBase(k), sprintf('baseline %.3f', cumBase(k)), ...
        'FontSize',fs_tick,'Color',[0.25 0.25 0.25],'Interpreter','none', ...
        'VerticalAlignment','middle','HorizontalAlignment','left');
end
% 层内占比：分母 = 该场景的流出总量（三条通路 + Q_BBB 反号时的经 BBB 回流血），
% 所以同一根柱上所有标注之和恒为 100%；取整用最大余数法，避免各自四舍五入后
% 出现 99 或 101（未反号时灰层为 0，分母与三通路总量相同，其余 13 列不受影响）。
totS = sum(ST,2);
pctL = zeros(numel(CODES), size(ST,2));
for r = 1:numel(CODES)
    pctL(r,:) = local_round100(100*ST(r,:)/totS(r));
end
cumBot = zeros(1,numel(CODES));
for li = 1:size(ST,2)
    for r = 1:numel(CODES)
        if pctL(r,li) >= 1
            text(ax, r, cumBot(r)+ST(r,li)/2, sprintf('%d%%', pctL(r,li)), ...
                'HorizontalAlignment','center','VerticalAlignment','middle', ...
                'FontSize',fs_cell,'Color',C.white,'FontWeight','bold');
        end
    end
    cumBot = cumBot + ST(:,li)';
end
% 分组分隔线只画到柱高（组合列前加粗）
for g = 1:numel(GRPEND)-1
    if g == numel(GRPEND)-1, lw = LW_SEP_LAST; else, lw = LW_SEP; end
    plot(ax, [GRPEND(g)+0.5 GRPEND(g)+0.5], [0 max(totOut)], '-', 'Color',[0.1 0.1 0.1], ...
         'LineWidth',lw, 'HandleVisibility','off');
end
set(ax, 'XTick',1:numel(CODES), 'XTickLabel',SHORT, 'XTickLabelRotation',0, ...
        'TickLabelInterpreter','none', 'FontSize',fs_tick, ...
        'YGrid','off','Box','off');
ax.XAxis.FontSize = fs_xtick;   % 同上：标签不倾斜，字号略降以容纳 15 列
xlim(ax, [0.5 numel(CODES)+0.5]);      % 与 (a) 相同的 xlim，保证上下刻度对齐
ylim(ax, [0 0.40]);                    % 抬到 0.4，给轴内顶部图例留出空间
ylabel(ax, 'Efflux Rate (mL/min)');
ax.YLabel.FontSize = fs_ax;   % 与 Fig3/Fig4 的轴标题一致
% 柱顶标注总出口相对基线的百分比变化
for r = 1:numel(CODES)
    pv = 100*(sum(ST(r,:))/sum([getq('Q_OLS',iB),getq('Q_SSS',iB),getq('Q_SLS',iB)]) - 1);
    text(ax, r, sum(ST(r,:)) + 0.004, sprintf('%+.0f%%', pv), ...
        'HorizontalAlignment','center','VerticalAlignment','bottom', ...
        'FontSize',fs_tick-2,'Color',[0.15 0.15 0.15],'FontWeight','bold');
end
title(ax, '(b)  Total Efflux Pathway Distribution', ...
      'FontWeight','bold','FontSize',fs_title);
% 图例：轴内顶部，再整体上移 0.3 个字符高度，与柱顶百分比留出空隙
lg = legend(ax, bh, layerLabels, 'Location','north','FontSize',fs_tick,'Box','off', ...
       'Orientation','horizontal','NumColumns',numel(layerLabels));
drawnow;                                   % 先让 tiledlayout 定好轴位置
lg.Units = 'normalized';
legPos0 = lg.Position;
lg.Position = legPos0 + [0, LEG_UP*fs_tick*(2.54/72)/(ax.Position(4)*fig.Position(4)), 0, 0];
ax_b = ax;   %#ok<NASGU>  (tiledlayout 自行等宽排布，无需手动对齐)
fprintf('  (b) 基线总出口 %.4f mL/min；BBB 倒流层出现在 %d/%d 个场景（最大 %.4f mL/min）\n', ...
        getq('Q_OLS',iB)+getq('Q_SSS',iB)+getq('Q_SLS',iB), sum(bbbOut>1e-9), NCOMB, max(bbbOut));

%% ── 版面自检 ─────────────────────────────────────────
fprintf('  字号(pt): 刻度 %.1f | 横轴 %.1f | 面板标题 %.1f | 格子文字 %.1f\n', ...
    fs_tick, fs_xtick, fs_title, fs_cell);
for ic = NCOMB-1:NCOMB                       % 两个 A3 组合列
    fprintf('  A3 列 %-7s: P_ECS %+.1f%% | Q_BBB %+.1f%% (%.5f mL/min) | Q_GS %+.1f%% | Q_PAS %+.1f%% | Q_SPI %+.1f%%\n', ...
        SHORT{ic}, M(ic,5), M(ic,2), getq('Q_BBB', iS(ic)), M(ic,1), M(ic,3), M(ic,4));
    fprintf('              三通路合计 %.4f mL/min (%+.1f%%) | 灰色 BBB 倒流层 %.5f mL/min | 脊髓占比 %.1f%%\n', ...
        sum(FL(ic,:)), 100*(sum(FL(ic,:))/sum([getq('Q_OLS',iB),getq('Q_SSS',iB),getq('Q_SLS',iB)])-1), ...
        bbbOut(ic), SH(ic,3));
end
drawnow;
axp = ax_b.Position;  xl = xlim(ax_b);  yl = ylim(ax_b);  figW = fig.Position(3);
for k = 1:numel(hBaseTxt)
    e = hBaseTxt(k).Extent;                                   % 数据单位
    xNorm = axp(1) + axp(3)*((e(1)+e(3)) - xl(1))/diff(xl);   % 图窗归一化坐标
    if xNorm <= 1, st = 'OK'; else, st = '溢出画布'; end
    fprintf('  基线标注 %d 右边界 %.3f 图窗宽 (=%.2f cm，图宽 %.0f cm) %s\n', k, xNorm, xNorm*figW, figW, st);
end
fprintf('  (b) 图例上移 %.3f 字符高 = %.3f cm（轴高 %.2f cm）\n', ...
    LEG_UP, (lg.Position(2)-legPos0(2))*axp(4)*fig.Position(4), axp(4)*fig.Position(4));
% 横轴代号间距自检：按实际字号与字体测量每个代号的宽度，检查相邻两个是否重叠
% 注意 (a) 挂了色标，轴比 (b) 窄，必须取两格中较窄者来判定（否则会漏判重叠）
wAx = [ax_a.Position(3), ax_b.Position(3)] * figW;
colw = min(wAx)/NCOMB;                                  % 每列宽度 (cm)，取较窄的一格
wl = zeros(1,NCOMB);
for r = 1:NCOMB
    h = text(0,0,SHORT{r},'FontName','Arial','FontSize',fs_xtick, ...
             'Units','centimeters','Visible','off','Interpreter','none');
    wl(r) = h.Extent(3);  delete(h);
end
gap = colw - (wl(1:end-1)+wl(2:end))/2;                 % 相邻两代号所需宽度的一半和
[gmin, imin] = min(gap);
gapE = 0.5*colw - wl/2;                                 % 代号到面板边缘的余量；只对首/末代号有意义
% （中间代号不存在"边缘"问题，取 min(gapE) 会被最宽的中列误判，故只查首末两项）
if min([gmin, gapE(1), gapE(end)]) >= 0.05, st = 'OK'; else, st = '间距不足，请降低 fs_xtick 或加宽图幅!'; end
fprintf('  轴宽(a/b) %.2f/%.2f cm | 列宽取窄者 %.2f cm | 最宽代号 %s (%.2f cm)\n', ...
    wAx(1), wAx(2), colw, SHORT{find(wl==max(wl),1)}, max(wl));
fprintf('  横轴代号: 最紧相邻 %s|%s 余量 %.2f cm | 边缘余量 %.2f/%.2f cm %s\n', ...
    SHORT{imin}, SHORT{imin+1}, gmin, gapE(1), gapE(end), st);

%% ── 导出 + 复制脚本 ──────────────────────────────────
try, java.lang.System.setProperty('user.home', getenv('TEMP')); catch, end
exportgraphics(fig, outPdf, 'ContentType','vector','Resolution',300);
fprintf('✓ 图已生成: %s\n', outPdf);
try
    thisFile = [mfilename('fullpath') '.m'];
    if ~strcmpi(fileparts(thisFile), fileparts(outPdf))
        copyfile(thisFile, fullfile(fileparts(outPdf),'draw_fig_comm_hydro.m'));
        fprintf('  脚本副本: %s\n', fullfile(fileparts(outPdf),'draw_fig_comm_hydro.m'));
    end
catch err
    fprintf('  脚本复制失败: %s\n', err.message);
end

%% ── 控制台汇总 ───────────────────────────────────────
fprintf('\n--- 热图矩阵 (%% vs baseline) ---\n');
fprintf('%-10s', 'code');  fprintf('%9s', QCOLS{:});  fprintf('\n');
for r = 1:numel(CODES)
    fprintf('%-10s', CODES{r});
    fprintf('%9.1f', M(r,:));
    fprintf('\n');
end
fprintf('\n--- 三条通路占比 (%%) ---\n');
fprintf('%-10s %8s %8s %8s\n','code','OLS','SSS','SLS');
for r = 1:numel(CODES)
    fprintf('%-10s %8.2f %8.2f %8.2f\n', CODES{r}, SH(r,1), SH(r,2), SH(r,3));
end
nSat = sum(abs(M(:)) > HM.clim);
fprintf('\n色标 ±%d%%，饱和单元格 %d 个（数值仍标出）\n', HM.clim, nSat);
fprintf('\n--- 层内占比（最大余数法取整，逐列之和应为 100）---\n');
for r = 1:numel(CODES)
    fprintf('  %-7s', SHORT{r});
    if size(ST,2) == 4
        fprintf(' OLS %2d | SSS %2d | SLS %2d | 灰 %2d', pctL(r,1), pctL(r,2), pctL(r,3), pctL(r,4));
    else
        fprintf(' OLS %2d | SSS %2d | SLS %2d', pctL(r,1), pctL(r,2), pctL(r,3));
    end
    fprintf('   和 %3d %s\n', sum(pctL(r,:)), string(repmat('OK',1,sum(pctL(r,:))==100)) + string(repmat('  <-- 不为 100!',1,sum(pctL(r,:))~=100)));
end
fprintf('=== DONE ===\n');
end

%% ════════════════════════════════════════════════════════
%  辅助函数
%% ════════════════════════════════════════════════════════
function v = local_col(T, name, idx)
if ~ismember(name, T.Properties.VariableNames)
    error('draw_fig_comm_hydro:noCol','表里缺少列 %s', name);
end
col = T.(name);
v = col(idx);
if iscell(v), v = cell2mat(v); end
v = double(v);
end

function cmap = local_diverging(n, negCol, zeroCol, posCol)
% 三段线性插值的发散色标（与 DrawResult0520 的热图端点一致）
half = floor(n/2);
cmap = zeros(n,3);
t1 = linspace(0,1,half)';
t2 = linspace(0,1,n-half)';
for k = 1:3
    cmap(1:half,k)     = negCol(k)  + (zeroCol(k)-negCol(k)) * t1;
    cmap(half+1:end,k) = zeroCol(k) + (posCol(k)-zeroCol(k)) * t2;
end
end

function s = local_round100(v)
% 最大余数法取整：各项取整后之和恰为 100（避免各自四舍五入后得到 99 或 101）
f = floor(v);
need = round(100 - sum(f));
if need > 0
    [~, ord] = sort(v - f, 'descend');
    f(ord(1:need)) = f(ord(1:need)) + 1;
elseif need < 0
    [~, ord] = sort(v - f, 'ascend');
    f(ord(1:-need)) = f(ord(1:-need)) - 1;
end
s = f;
end
